import Vuetify, {
  VApp,
  VNavigationDrawer,
  VToolbar,
  VToolbarItems,
  VTooltip,
  VBtn,
  VSpacer,
  VContent,
  VContainer,
  VCheckbox,
  VLayout,
  VFlex,
  VCard,
  VCardTitle,
  VTextField,
  VForm,
  VImg,
  VDivider,
  VIcon,
  VList,
  VListTile,
  VListTileTitle,
  VMenu,
  VExpansionPanel,
  VExpansionPanelContent,
  VCardText,
  VChip,
} from "vuetify/lib";

export default ({ Vue, router, options }) => {
  Vue.use(Vuetify, {
    components: {
      VApp,
      VNavigationDrawer,
      VToolbar,
      VToolbarItems,
      VTooltip,
      VBtn,
      VSpacer,
      VContent,
      VContainer,
      VCheckbox,
      VLayout,
      VFlex,
      VCard,
      VCardTitle,
      VTextField,
      VForm,
      VImg,
      VDivider,
      VIcon,
      VList,
      VListTile,
      VListTileTitle,
      VMenu,
      VExpansionPanel,
      VExpansionPanelContent,
      VCardText,
      VChip,
    },
    theme: {
      primary: "#1263CC",
    },
  });

  var redirect_dict = {
    "/#export": "/core/software/pupil-player/#export",
    "/#surface-tracking": "/core/software/pupil-capture/#surface-tracking",
    "/#analysis-plugins": "/core/software/pupil-player/#analysis-plugins",
    "/#pupil-capture": "/core/software/pupil-capture/",
    "/#pupil-player": "/core/software/pupil-player/",
    "/#network-plugins": "/core/software/pupil-capture/#network-plugins",
    "/#interprocess-and-network-communication": "/developer/core/network-api/",
    "/#annotations": "/core/software/pupil-capture/#annotations",

    "/invisible/user-guide/invisible-companion-app/#local-transfer": "/invisible/how-tos/data-collection-with-the-companion-app/transfer-recordings-via-usb",
    "/invisible/how-tos/data-collection-with-the-companion-app/transfer-recordings-via-usb": "/invisible/how-tos/data-collection-with-the-companion-app/transfer-recordings-via-usb",
    "/cloud/enrichments/#reference-image-mapper": "/invisible/enrichments/reference-image-mapper/",
    "/invisible/explainers/enrichments": "/invisible/enrichments",
    "/invisible/explainers/enrichments/#reference-image-mapper": "/invisible/enrichments/reference-image-mapper/",
    "/invisible/explainers/enrichments/#marker-mapper": "/invisible/enrichments/marker-mapper/",
    "/invisible/explainers/enrichments/#face-mapper": "/invisible/enrichments/face-mapper/",
    "/invisible/explainers/enrichments/#gaze-overlay": "/invisible/enrichments/gaze-overlay/",
    "/invisible/explainers/enrichments/#raw-data": "/invisible/enrichments/raw-data/",
    "/invisible/explainers/data-streams/": "/invisible/basic-concepts/data-streams/",
    "/invisible/explainers/basic-concepts/": "/invisible/basic-concepts/data-streams/",
    "/invisible/explainers/basic-concepts/#recordings": "/invisible/basic-concepts/recordings-wearers-and-templates/#recordings",
    "/invisible/explainers/basic-concepts/#wearers": "/invisible/basic-concepts/recordings-wearers-and-templates/#wearers",
    "/invisible/explainers/basic-concepts/#templates": "/invisible/basic-concepts/recordings-wearers-and-templates/#templates",
    "/invisible/explainers/basic-concepts/#projects": "/invisible/basic-concepts/projects-and-workspaces/#projects",
    "/invisible/explainers/basic-concepts/#workspaces": "/invisible/basic-concepts/projects-and-workspaces/#workspaces",
    "/invisible/explainers/glasses-and-companion-device/": "/invisible/glasses-and-companion/technical-overview/",
    "/invisible/explainers/glasses-and-companion-device/#pupil-invisible-glasses": "/invisible/glasses-and-companion/technical-overview/",
    "/invisible/explainers/glasses-and-companion-device/#pupil-invisible-companion-device": "/invisible/glasses-and-companion/companion-device/",
    "/invisible/explainers/publications.html": "/invisible/publications/",
    "/invisible/explainers/publications": "/invisible/publications/",
    "/invisible/how-tos/pupil-invisible-glasses/exchange-lenses.html": "/invisible/glasses-and-companion/hardware-handling/exchange-lenses/",
    "/invisible/how-tos/pupil-invisible-glasses/clean-and-disinfect.html": "/invisible/glasses-and-companion/hardware-handling/clean-and-disinfect/",
    "/invisible/how-tos/pupil-invisible-glasses/attach-the-head-strap.html": "/invisible/glasses-and-companion/hardware-handling/attach-the-head-strap/",
    "/invisible/how-tos/integrate-with-the-real-time-api/introduction/": "/invisible/real-time-api/introduction/",
    "/invisible/how-tos/integrate-with-the-real-time-api/track-your-experiment-progress-using-events/": "/invisible/real-time-api/track-your-experiment-progress-using-events/",
    "/invisible/how-tos/integrate-with-the-real-time-api/integrate-with-the-real-time-api/track-your-experiment-in-matlab'/": "/invisible/real-time-api/integrate-with-the-real-time-api/track-your-experiment-in-matlab/",
    "/invisible/how-tos/integrate-with-the-real-time-api/legacy-api.html": "/invisible/real-time-api/legacy-api/",
    "/cloud/": "/invisible/",
  };

  router.beforeEach((to, from, next) => {
    if (Object.keys(redirect_dict).indexOf(to.fullPath) >= 0) {
      next({ path: redirect_dict[to.fullPath] });
    } else {
      next();
    }
  });
};
