name: Build/Deploy to Production

on:
  push:
    branches: ["master"]
  workflow_dispatch: # this makes the action manual

jobs:
  build:
    name: 📦 ${{ matrix.component }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [neon, invisible, core, alpha-lab, landing-page]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Make build
        working-directory: ./${{ matrix.component }}
        run: pnpm run docs:build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}
          path: ${{ matrix.component }}/.vitepress/dist

      - name: Get built HTML files
        id: html-files
        run: |
          html_files=$(find ./${{ matrix.component }}/.vitepress/dist -name '*.html')
          html_files="${html_files//$'\n'/ }"
          html_files="${html_files//$'\r'/ }"
          echo "all_html_files=${html_files}" >> $GITHUB_ENV

  debugging-info:
    name: Upload Debugging Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write commit SHA to gitcommit.txt
        shell: bash
        run: echo $GITHUB_SHA > gitcommit.txt

      - name: Upload Git Commit Info
        uses: actions/upload-artifact@v4
        with:
          name: gitcommit
          path: gitcommit.txt

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://docs-staging.pupil-labs.com
    needs: [build, debugging-info]

    steps:
      - uses: actions/checkout@v4

      - name: Get size of files
        shell: bash
        run: |
          du -ah .

      - name: Download gitcommit
        uses: actions/download-artifact@v4
        with:
          name: gitcommit
          path: gitcommit.txt

      - name: Download Neon
        uses: actions/download-artifact@v4
        with:
          name: neon
          path: neon/

      - name: Download Invisible
        uses: actions/download-artifact@v4
        with:
          name: invisible
          path: invisible/

      - name: Download Core
        uses: actions/download-artifact@v4
        with:
          name: core
          path: core/

      - name: Download AlphaLab
        uses: actions/download-artifact@v4
        with:
          name: alpha-lab
          path: alpha-lab/

      - name: Download Landing Page
        uses: actions/download-artifact@v4
        with:
          name: landing-page

      - name: Rsync action - Deploy to staging
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -hrvz --delete --exclude=".htaccess"
          path: .
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST}}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

  deploy-production:
    name: Deploy to production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://docs.pupil-labs.com

    steps:
      - uses: actions/checkout@v4

      - name: Download Neon
        uses: actions/download-artifact@v4
        with:
          name: neon
          path: neon/

      - name: Download Invisible
        uses: actions/download-artifact@v4
        with:
          name: invisible
          path: invisible/

      - name: Download Core
        uses: actions/download-artifact@v4
        with:
          name: core
          path: core/

      - name: Download AlphaLab
        uses: actions/download-artifact@v4
        with:
          name: alpha-lab
          path: alpha-lab/

      - name: Download Landing Page
        uses: actions/download-artifact@v4
        with:
          name: landing-page

      - name: Rsync action - Deploy to production
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -hrvz --delete --exclude=".htaccess"
          path: .
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST}}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
