name: Build only

on: pull_request

jobs:
  build:
    name: 📦 ${{ matrix.component }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [neon, invisible, core, alpha-lab, landing-page]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.6

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Make build
        working-directory: ./${{ matrix.component }}
        run: pnpm run docs:build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}
          path: ${{ matrix.component }}/.vitepress/dist

      - name: Get built HTML files
        id: html-files
        run: |
          html_files=$(find ./${{ matrix.component }}/.vitepress/dist -name '*.html')
          html_files="${html_files//$'\n'/ }"
          html_files="${html_files//$'\r'/ }"
          echo "all_html_files=${html_files}" >> $GITHUB_ENV

  debugging-info:
    name: Upload Debugging Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write commit SHA to gitcommit.txt
        shell: bash
        run: echo $GITHUB_SHA > gitcommit.txt

      - name: Upload Git Commit Info
        uses: actions/upload-artifact@v4
        with:
          name: gitcommit
          path: gitcommit.txt
